"""Two-factor authentication: time-based one-time codes (RFC 6238 TOTP), as used by
Google Authenticator, Microsoft Authenticator, Authy and similar apps.

- The shared secret is encrypted at rest with a key derived from the installation's
  PHARMACY_SECRET_KEY (generated by the installer, never in Git).
- Codes are 6 digits, 30-second steps, ±1 step of clock drift; a code that was
  used once is refused again (replay guard).
- Ten one-time recovery codes are issued at enrolment, stored only as hashes.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import io
import secrets
import struct
import time
from urllib.parse import quote

from app.config import SECRET_KEY

ISSUER = "Faheem Pharmacy"
DIGITS, PERIOD, DRIFT = 6, 30, 1


def new_secret() -> str:
    return base64.b32encode(secrets.token_bytes(20)).decode().rstrip("=")


def _key(secret: str) -> bytes:
    s = secret.upper().replace(" ", "")
    return base64.b32decode(s + "=" * (-len(s) % 8))


def code_at(secret: str, step: int) -> str:
    mac = hmac.new(_key(secret), struct.pack(">Q", step), hashlib.sha1).digest()
    off = mac[-1] & 0x0F
    value = (struct.unpack(">I", mac[off:off + 4])[0] & 0x7FFFFFFF) % (10 ** DIGITS)
    return str(value).zfill(DIGITS)


def current_step(now: float | None = None) -> int:
    return int((time.time() if now is None else now) // PERIOD)


def verify(secret: str, code: str, last_step: int | None = None, now: float | None = None) -> int | None:
    """The time step the code belongs to, or None. Steps at or before ``last_step`` are refused (replay)."""
    code = "".join(ch for ch in str(code or "") if ch.isdigit())
    if len(code) != DIGITS or not secret:
        return None
    step = current_step(now)
    for s in range(step - DRIFT, step + DRIFT + 1):
        if last_step is not None and s <= last_step:
            continue
        if hmac.compare_digest(code_at(secret, s), code):
            return s
    return None


def provisioning_uri(secret: str, username: str) -> str:
    label = quote(f"{ISSUER}:{username}")
    return f"otpauth://totp/{label}?secret={secret}&issuer={quote(ISSUER)}&digits={DIGITS}&period={PERIOD}&algorithm=SHA1"


def qr_data_uri(text: str) -> str:
    import qrcode

    img = qrcode.make(text, box_size=6, border=2)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


# --------------------------------------------------------------------------- secret at rest
def _fernet():
    from cryptography.fernet import Fernet

    return Fernet(base64.urlsafe_b64encode(hashlib.sha256(("faheem-mfa:" + SECRET_KEY).encode()).digest()))


def seal(secret: str) -> str:
    return _fernet().encrypt(secret.encode()).decode()


def unseal(token: str | None) -> str:
    if not token:
        return ""
    from cryptography.fernet import InvalidToken

    try:
        return _fernet().decrypt(token.encode()).decode()
    except InvalidToken:
        return ""            # the installation's secret key changed: the user must enrol again (manage.py user reset-2fa)


# --------------------------------------------------------------------------- recovery codes
def new_recovery_codes(n: int = 10) -> list[str]:
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"          # no 0/O/1/I confusion
    return ["-".join("".join(secrets.choice(alphabet) for _ in range(4)) for _ in range(2)) for _ in range(n)]


def hash_recovery(code: str) -> str:
    norm = "".join(ch for ch in code.upper() if ch.isalnum())
    return hashlib.sha256(("faheem-recovery:" + SECRET_KEY + ":" + norm).encode()).hexdigest()


def use_recovery(hashes: list[str] | None, code: str) -> list[str] | None:
    """Remaining hashes after spending ``code``, or None when it is not a valid unused code."""
    h = hash_recovery(code)
    hashes = list(hashes or [])
    for stored in hashes:
        if hmac.compare_digest(stored, h):
            hashes.remove(stored)
            return hashes
    return None
