"""initial schema

Revision ID: 06d341a835c2
Revises: 
Create Date: 2026-09-13 00:52:59.363284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d341a835c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('generic_name', sa.String(length=250), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('pack_size', sa.String(length=60), nullable=False),
    sa.Column('strength', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_article_id'), ['article_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_type', sa.String(length=40), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)

    op.create_table('number_sequences',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('gst_number', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('doctor_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_id'), ['customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=60), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_purchase_date'), ['purchase_date'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'batch_no', 'expiry_date', name='uq_batch_item_no_exp')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('ix_batches_expiry', ['expiry_date'], unique=False)

    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followups_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_status'), ['status'], unique=False)

    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('voucher', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=10), nullable=False),
    sa.Column('payment_status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_payment_mode'), ['payment_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_sale_date'), ['sale_date'], unique=False)

    op.create_table('expiry_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('settled_quantity', sa.Integer(), nullable=False),
    sa.Column('settled_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('settled_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settled_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expiry_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expiry_alerts_status'), ['status'], unique=False)

    op.create_table('purchase_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_returns_return_date'), ['return_date'], unique=False)

    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('purchase_item_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(length=250), nullable=False),
    sa.Column('raw_batch', sa.String(length=60), nullable=False),
    sa.Column('raw_expiry', sa.String(length=30), nullable=False),
    sa.Column('raw_quantity', sa.Integer(), nullable=False),
    sa.Column('raw_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('raw_mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('best_match_item_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['best_match_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.ForeignKeyConstraint(['purchase_item_id'], ['purchase_items.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_status'), ['status'], unique=False)

    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('batch_no', sa.String(length=60), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('adjustment_date', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_adjustments_adjustment_date'), ['adjustment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_adjustments_category'), ['category'], unique=False)

    # ### end Alembic commands ###

    # Full-text search (FTS5) structures are not representable in SQLAlchemy
    # metadata, so they are created explicitly here. `app.database.ensure_fts`
    # also applies them idempotently at runtime.
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS items_fts USING fts5("
        "name, generic_name, manufacturer, barcode, "
        "content='items', content_rowid='id', tokenize='unicode61')"
    )
    op.execute(
        "CREATE TRIGGER IF NOT EXISTS items_fts_ai AFTER INSERT ON items BEGIN "
        "INSERT INTO items_fts(rowid, name, generic_name, manufacturer, barcode) "
        "VALUES (new.id, new.name, new.generic_name, new.manufacturer, new.barcode); END"
    )
    op.execute(
        "CREATE TRIGGER IF NOT EXISTS items_fts_ad AFTER DELETE ON items BEGIN "
        "INSERT INTO items_fts(items_fts, rowid, name, generic_name, manufacturer, barcode) "
        "VALUES ('delete', old.id, old.name, old.generic_name, old.manufacturer, old.barcode); END"
    )
    op.execute(
        "CREATE TRIGGER IF NOT EXISTS items_fts_au AFTER UPDATE ON items BEGIN "
        "INSERT INTO items_fts(items_fts, rowid, name, generic_name, manufacturer, barcode) "
        "VALUES ('delete', old.id, old.name, old.generic_name, old.manufacturer, old.barcode); "
        "INSERT INTO items_fts(rowid, name, generic_name, manufacturer, barcode) "
        "VALUES (new.id, new.name, new.generic_name, new.manufacturer, new.barcode); END"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS items_fts_au")
    op.execute("DROP TRIGGER IF EXISTS items_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS items_fts_ai")
    op.execute("DROP TABLE IF EXISTS items_fts")
    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_category'))
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_adjustment_date'))

    op.drop_table('stock_adjustments')
    op.drop_table('sale_items')
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_queue_status'))

    op.drop_table('review_queue')
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_returns_return_date'))

    op.drop_table('purchase_returns')
    with op.batch_alter_table('expiry_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expiry_alerts_status'))

    op.drop_table('expiry_alerts')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_mode'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_no'))

    op.drop_table('sales')
    op.drop_table('purchase_items')
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followups_status'))
        batch_op.drop_index(batch_op.f('ix_followups_due_date'))

    op.drop_table('followups')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index('ix_batches_expiry')

    op.drop_table('batches')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_purchases_invoice_no'))

    op.drop_table('purchases')
    op.drop_table('login_sessions')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_mobile'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_id'))

    op.drop_table('customers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_employee_id'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))

    op.drop_table('suppliers')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('number_sequences')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_due_date'))

    op.drop_table('notifications')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_category'))
        batch_op.drop_index(batch_op.f('ix_items_barcode'))
        batch_op.drop_index(batch_op.f('ix_items_article_id'))

    op.drop_table('items')
    # ### end Alembic commands ###
