"""invoice extraction evidence fields

Revision ID: a3c9836038a1
Revises: 48f48dc87018
Create Date: 2026-09-16 14:48:34.773387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c9836038a1'
down_revision: Union[str, Sequence[str], None] = '48f48dc87018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_raw', sa.String(length=250), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('quantity_free', sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('quantity_raw', sa.String(length=30), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('source_serial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('validation_status', sa.String(length=20), nullable=False, server_default=sa.text("''")))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_sha256', sa.String(length=64), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('document_type', sa.String(length=30), nullable=False, server_default=sa.text("''")))
        batch_op.add_column(sa.Column('extraction_meta', sa.Text(), nullable=False, server_default=sa.text("''")))

    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_quantity_free', sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(sa.Column('source_serial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_reasons', sa.String(length=250), nullable=False, server_default=sa.text("''")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_column('review_reasons')
        batch_op.drop_column('source_page')
        batch_op.drop_column('source_serial')
        batch_op.drop_column('raw_quantity_free')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('extraction_meta')
        batch_op.drop_column('document_type')
        batch_op.drop_column('source_sha256')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_column('validation_status')
        batch_op.drop_column('source_page')
        batch_op.drop_column('source_serial')
        batch_op.drop_column('quantity_raw')
        batch_op.drop_column('quantity_free')
        batch_op.drop_column('description_raw')
    # ### end Alembic commands ###
